# permissions for end users to edit mcspcustomers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mcspcustomer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mcsp-operator-new
    app.kubernetes.io/part-of: mcsp-operator-new
    app.kubernetes.io/managed-by: kustomize
  name: mcspcustomer-editor-role
rules:
- apiGroups:
  - mcsp.mcsp.io
  resources:
  - mcspcustomers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcsp.mcsp.io
  resources:
  - mcspcustomers/status
  verbs:
  - get
